# Generated by Django 4.2.6 on 2024-02-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Spa', 'Spa'), ('Aromatherapy', 'Aromatherapy'), ('Massage', 'Massage'), ('Yoga', 'Yoga')], max_length=15)),
                ('date', models.DateTimeField(verbose_name='XYZ DateTime')),
                ('hour', models.CharField(choices=[('9:00', '9:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('16:00', '16:00')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
