# Generated by Django 4.2.6 on 2024-02-16 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
